apiVersion: apps/v1
kind: Deployment
metadata:
  name: global-continuum-placement
  labels:
    app.kubernetes.io/name: global-continuum-placement
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: global-continuum-placement
  template:
    metadata:
      labels:
        app.kubernetes.io/name: global-continuum-placement
    spec:
      containers:
      - name: app
        image: ryaxtech/global-continuum-placement:main
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http-api
        env:
          - name: ORCHESTRATOR_BASE_API
            value: http://physics-work-translator.physics-atos/api/v1/
          - name: INFERENCE_ENGINE_BASE_API
            value: https://semantics-block.apps.ocphub.physics-faas.eu/api/v2/
          - name: INFERENCE_ENGINE_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: inference-engine-api-key
                key: key
---
apiVersion: v1
kind: Service
metadata:
  name: global-continuum-placement
spec:
  selector:
    app.kubernetes.io/name: global-continuum-placement
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-api
